# Generated by Django 5.2.7 on 2025-10-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_point',
            field=models.IntegerField(default=10),
        ),
    ]
