# Generated by Django 5.2.7 on 2025-10-24 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_user_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_point',
        ),
    ]
