# Generated by Django 5.2.7 on 2025-10-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
