# Generated by Django 5.2.7 on 2025-10-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_task_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
    ]
